# EFA {#efa}

```{r, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE, warning = FALSE, message = FALSE
)
```


```{r, include=FALSE}
library(data.table)
library(glue)
library(lavaan)
library(googlesheets4)
library(kableExtra)
library(psych)
library(GPArotation)
library(nFactors)
# 
# questions <- fread('./data/questions.csv')
# c2_data <- fread('./data/c2_data.csv')
# questionnaire_names <- fread('./data/questionnaire_names.csv')
# 
# c2_info <- questionnaire_names[question_type == 'competencies']
# c2_questions <- c2_info[order(q_order), question_ru]
# c2_q_numbers <- c2_info[order(q_order), q]
# 
# c2_names <- questions[question_ru %in% c2_info[, unique(question_ru)], sort(unique(c2))]
# c3_names <- questions[question_ru %in% c2_info[, unique(question_ru)], sort(unique(c3))]
# 
# fit_c3_mlr <- readRDS('fit_c3_mlr')
# c3_models <- readRDS('c3_models')
# 
# fit_mlr_cleaned <- readRDS('fit_mlr_cleaned')
# coeffs_cleaned <- data.table(parameterEstimates(fit_mlr_cleaned))[op == '=~']
# coeffs_cleaned_lowp <- coeffs_cleaned[pvalue < 0.05 | is.na(pvalue)]
# coeffs_cleaned[pvalue >= 0.05, .N]
```

```{r}
get_loadings <- function(obj) {
  loadings_matrix <- unclass(obj$loadings)
  loadings_dt <- as.data.table(loadings_matrix, keep.rownames = 'q')
  
  loadings_dt[, h2 := obj$communality]
  loadings_dt[, u2 := obj$uniquenesses]
  loadings_dt[, com := obj$complexity]
  
  loadings_dt[, max_loading := do.call(pmax, lapply(.SD, abs)), .SDcols = patterns('ML')]

  loadings_dt[, list(
    total_items = .N,
    loadings_03 = sum(max_loading > 0.3),
    communality_weak = sum(h2 < 0.4),
    complexity_high = sum(com > 2)
  )]  
}

get_scree_plot <- function(df) {
  ev <- eigen(cor(df))$values
  ap <- parallel(subject = nrow(df), var = ncol(df), rep = 100, cent = .05)
  
  nS <- nScree(x = ev, aparallel = ap$eigen$qevpea)
  plotnScree(nS)  
}

```



