# Questions {#q}


## несбалансированность шкал

1. Я не знаю, что делать с шкалами с разными по численности вопросов. В одной шкале три вопроса, в другой -- 28 вопросов. Модель с отдельными суб-шкалами на 2-6 вопросов не сошлась, то есть нельзя просто взять и весь опросник превратить в 30 небольших шкал. Переход на уровень выше, где всего 5 макрошкал, также не сильно облегчит ситуацию -- там 13, 33, 28, 21 и 17 вопросов (после удаления вопросов, которые не дают вклад в 8 целевых шкал)

Я вижу несколько вариантов здесь:

- исходя из теоретических обоснований каждую из крупных 8 шкал разделить на на 2-3 субшкалы, в среднем по 10 вопросов. Так, шкалу `отношения-1`, в которой 21 вопрос, можно попробовать разделить на две части исходя из своих представлений, какими могут быть два фактора в этих вопросах.

- можно попробовать использовать факторный анализ для разделения крупных шкал на субшкалы. Однако, судя по первым попыткам, в каждой из крупных шкал есть достаточно много вопросов, которые вообще не делают вклад в эти шкалы. То есть, возможно эти вопросы просто лишние. К тому же шкала `отношения-1` вообще  выглядит как одна шкала, так как в ней формируется один большой фактор, остальное по остаточному принципу или вообще без вкладов.

## качество модели

Невысокие значения метрики CFI говорят, что, возможно, факторная структура (шкалы и соответствующие им вопросы) несколько не соответствует тому, что наблюдается в данных -- например часть вопросов может быть отнесена к другим факторам или иметь отношение сразу к нескольким факторам. То, что более мелкие модели по субшкалам не сходятся или имеют не очень высокое качество моделей, косвенно подтверждает эту идею. Аналогично, когда я делаю эксплораторный факторный анализ, субшкалы одной компетенции (например, 8 субшкал в рамках `отношения-1`), достаточно много вопросов оказываются без значимых нагрузок (бесполезны для факторов). Когда я смотрел корреляции некоторых субшкал, некоторые вообще ни с чем не коррелировали. Само по себе вполне нормальная ситуация, но от группы компетенций я бы ожидал все же какой-то внутренней взаимосвязи все же.

В общем, это меня приводит к двум идеям:

- попробовать сделать кросс-нагрузки. То есть в моделях указать, что некоторые вопросы могут относитеться еще и к другим факторам. И попробоватьп посмотреть, что получится с такой моделью. Мне не очень нравится этот подход, так что потом будет достаточно сложно вывести правило, как считать баллы по компетенциям.

- начать с самого начала и попробовать пересмотреть, какие вообще факторы получаются на полученных ответах и насколько они различаются от предположенных теоретических факторов (компетенций). То есть сделать эксплораторный факторный анализ по всем вопросам. Однако этот путь предполагает, что теор.модель из статьи неточная. И непонятно, как учесть те вопросы и субшкалы из исходных 230, которые вы исключили из опросника.