--- 
title: "Валидация опросника"
# subtitle: "в исследованиях поведения покупателей"
author: 'Ph.A.Upravitelev '
date: "`r Sys.Date()`"
documentclass: book
link-citations: yes
lang: ru-RU
site: bookdown::bookdown_site
---

# Intro

## Content

Раздел [Data preparation](#preprocessing) посвящен подготовке данных -- перекодированию названий вопросов, перекодированию текстовых значений ответов в числовые, перекодирование обратных вопросов и т. д.

Раздел [Descriptives](#descriptives) содержит в себе распределение отуствующих вопросов по шкалам и субшкалам, корреляционный анализ шкал и субшкал, оценку динамики вариативности ответов в зависимости от порядка предъявления (чтобы проверить, не устали ли респонденты отвечать на вопросы). 

Раздел [EFA](#efa) посвящен эксплораторной оценке факторной структуры опросника --- насколько хорошая получается факторная структура, если извлекать столько же факторов, сколько в теоретической модели. Также я сделал оценку моделей каком разном количестве факторов. Отдельно я проанализировал структуру крупных шкал -- есть ли там нерелевантные вопросы, насколько хорошо повторяется теоретическая структура субшкал и т. д.

Раздел [CFA](#cfa) посвящен конфирматорной оценке теоретической модели шкал на основе данных опросника. А также попыткам улучшить модель. Я попробовал несколько способов улучшить качество модели:

- исходная модель
- модель с удалением вопросов, не делающих значимый вклад
- модель с указанием кросс-факторных вкладов вопросов
- модель с удалением вопросов с высокими кросс-факторными нагрузками
- модель с удалением вопросов, которые в восьмифакторной EFA-модели имели низкие факторные нагрузки
- модель с коррекцией крупных шкал (удалением вопросов с низкой нагрузкой в факторы шкалы)

В разделе [New model](newmodel) я пробую переструктурировать опросник и выделить осмысленное количество факторов. В результате у меня получилось два достаточно близких по метрикам и смыслам решения с 13 и 14 факторами. 

Разделе [Convergent validity](#cv) посвящен оцененке конвергентной валидности выделенных шкал опросника -- насколько новые шкалы (при 13- и 14-ти факторных решениях) коррелируют с другими личностными опросниками и шкалами.

Раздел [Summary](#s) --- коротко результаты работы и дальнейшие действия.


## Model and applications

https://docs.google.com/spreadsheets/d/1kjfYXDjMQ-RXZSFKUem_ABaXFhO1qg6Y4KLeFZD0DeM/edit?gid=1547686518#gid=1547686518
